apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: platform-provisioner-binding
subjects:
  - kind: ServiceAccount
    name: backend-sa
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: platform-provisioner
  apiGroup: rbac.authorization.k8s.io
