apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: platform-provisioner
rules:
  # Namespace lifecycle
  - apiGroups: [""]
    resources: ["namespaces"]
    verbs: ["create", "get", "list", "watch", "delete"]
  # Allow Helm to manage NetworkPolicies for store charts
  - apiGroups: ["networking.k8s.io"]
    resources: ["networkpolicies"]
    verbs: ["get", "list", "watch"]
  # Core resources inside store namespaces
  # Allow Helm charts to manage PodDisruptionBudgets
  - apiGroups: ["policy"]
    resources: ["poddisruptionbudgets"]
    verbs: ["create", "get", "list", "watch", "delete"]

  - apiGroups: [""]
    resources:
      - pods
      - services
      - persistentvolumeclaims
      - secrets
      - configmaps
      - serviceaccounts
    verbs: ["create", "get", "list", "watch", "delete"]

  # Workloads
  - apiGroups: ["apps"]
    resources:
      - deployments
      - statefulsets
    verbs: ["create", "get", "list", "watch", "delete"]

  # Ingress
  - apiGroups: ["networking.k8s.io"]
    resources: ["ingresses"]
    verbs: ["create", "get", "list", "watch", "delete"]
